### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by koteesy** [playwright-community/playwright-go#254]
Trying to install package
```
go get github.com/playwright-community/playwright-go
```
I got

```
go: github.com/playwright-community/playwright-go upgrade => v0.1400.0
go get: github.com/playwright-community/playwright-go@v0.1400.0: parsing go.mod:
        module declares its path as: github.com/mxschmitt/playwright-go
                but was required as: github.com/playwright-community/playwright-go
```

**Comment by octoper** [comment]
You have to run `go get github.com/mxschmitt/playwright-go` instead of `go get github.com/playwright-community/playwright-go`, that might be occurs because it is not updated in the Go proxy.

**Comment by mxschmitt** [comment]
This should be fixed with the latest release, it includes the renaming.

**Comment by NuLL3rr0r** [comment]
I still have this issue and I see it as closed. Has it really been solved?

```
go: finding module for package github.com/mxschmitt/playwright-go
go: found github.com/mxschmitt/playwright-go in github.com/mxschmitt/playwright-go v0.2000.1
go: XXXXXXXXXXXXX imports
	github.com/mxschmitt/playwright-go: github.com/mxschmitt/playwright-go@v0.2000.1: parsing go.mod:
	module declares its path as: github.com/playwright-community/playwright-go
	        but was required as: github.com/mxschmitt/playwright-go
```

**Comment by NuLL3rr0r** [comment]
Never mind, [the sample here](https://playwright.tech/blog/automate-browsers-with-golang) imports the module from the old repo. I changed that and it works now.
